## Defning vectors

In [1]:
# Defining a Vector
import numpy as np

# single dimension array is vector 
x = [1,2,3]
vector = np.array(x)
vector

array([1, 2, 3])

In [2]:
# Vector created is single dimension array
vector.ndim

1

In [3]:
# Shape of the vector: single dimension
vector.shape

(3,)

## Arithmetic operations on Vectors

In [5]:
a = np.random.randint(10,50,size =5) 
b = np.random.randint(25,75,size = 5)
print(a)
print(b)
c = a + b
print("addition",c)

[27 35 13 20 26]
[70 64 35 30 36]
addition [97 99 48 50 62]


In [6]:
 a = np.random.randint(10,50,size =5) 
b = np.random.randint(25,75,size = 5)
print(a)
print(b)
c = a - b
print("difference",c)

[19 31 24 33 26]
[47 28 59 34 66]
difference [-28   3 -35  -1 -40]


In [7]:
 a = np.random.randint(10,50,size =5) 
b = np.random.randint(25,75,size = 5)
print(a)
print(b)
c = a * b
print("multiplication",c)

[33 44 32 30 17]
[45 54 63 66 50]
multiplication [1485 2376 2016 1980  850]


In [8]:
  a = np.random.randint(10,50,size =5) 
b = np.random.randint(25,75,size = 5)
print(a)
print(b)
c = a / b
print("division",c)

[18 35 24 10 17]
[25 29 38 46 51]
division [0.72       1.20689655 0.63157895 0.2173913  0.33333333]


## Vector Dot product


In [9]:
a = np.random.randint(10,50,size =5) 
b = np.random.randint(25,75,size = 5)
print(a)
print(b)


[46 32 12 14 18]
[68 54 67 50 49]


In [10]:
vector_dot = a.dot(b)
vector_dot

7242

In [11]:
x = np.arange(5,10)
y = np.arange(5)
print(x)
print(y)
vector_dot = x.dot(y)
print("dot product", vector_dot)

[5 6 7 8 9]
[0 1 2 3 4]
dot product 80


## Vector Scalar Multiplication

In [12]:
x = np.arange(5,10)
vs = 3 * x
print("vector scalar multiplication" , vs)

vector scalar multiplication [15 18 21 24 27]


In [13]:
x

array([5, 6, 7, 8, 9])